import type { NextPage } from 'next'
import Head from 'next/head'
import Menu from 'components/Menu'
import { FC } from 'react'
import Container from 'components/Container'
import Newboards from 'components/Newboards'
import H1 from 'components/TitlePage'
import Hardboards from 'components/Hardboards'

const Home: FC = () => {
  return (
    <div>
      <Head>
        <title>Code interview Brasil</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <Container>
        <>
          <H1>Code Interview Brasil</H1>
          <p>
            Este projeto tem como objetivo ajudar programdores a se sairem bem
            em entrevistas que contenham white label ou quadro branco em
            português.
          </p>
          <Newboards />
          <Hardboards />
          <div>divisão onde contem os códigos mais "complexos"</div>
          <div>divisão com os mais fáceis</div>
          <div>divisão com os links de livecoding legais</div>
          <div>divisão com livros sobre isto e diversas dicas</div>
        </>
      </Container>
    </div>
  )
}

export default Home
